### ISSUE TITLE
Would be nice to keep some of the derivs on the “Community Art” section changed and were dynamic, so you are not always seeing the same ones

### ISSUE THREAD

**Issue by chase-manning** [uwu-labs/uwucrew-site-v2#20]

**Comment by chase-manning** [comment]
@0xKiwi The community art section images are already dynamic. We could add more if that helps? But for now I'l close this issue as I think it's already implemented.

**Comment by 0xKiwi** [comment]
Yes! Pretty sure we solved this, thank you!
